name: Makefile CI

on:
  push:
    branches: [ "wasp-os" ]
  pull_request:
    branches: [ "wasp-os" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    #- name: configure
    #  run: git clone https://github.com/theocoutu/wasp-bootloader;cd wasp-bootloader

    - name: Install dependencies
      run: git submodule update --init --recursive

    - name: Run check
      run: make BOARD=rock_magic3_nrf52840

    #- name: Run distcheck
    #  run: make distcheck
